DataIngestion: 
  gold_ticker: "GC=F"
  train_start_date: "2021-01-02" 
  train_end_date: "2024-10-31"
  test_start_date: "2024-11-01"
  test_end_date: "2025-02-28"


Data_paths:
  train_file_name: "train.csv"
  test_file_name: "test.csv"
  train_data_path: "Artifacts/"
  test_data_path: "Artifacts/"